### PR TITLE
fixed #632: fixed issue that qr code was not vissible at some android phones.

### LINKED ISSUE #632: (Androld) QR code not shown on receive screen

### PR DESCRIPTION
**Pull request by crchemist-ip**
Also there is other fix available https://github.com/cssivision/react-native-qrcode/pull/70/files , but that PR not yet approved to react-native-qrcode.  Current PR tested with:
  * samsund a6
  * iphone 6

### CODE REVIEW

File: src/components/Receive/AddressDetail.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ type Props = {
 }
 
 const AddressDetail = ({address, translations}: Props) => (
-  <QRCode value={address} size={140} bgColor="#000" fgColor="#fff" />
+  <QRCode value={address} size={140} />
```
Comment (vantuz-subhuman) [inline src/components/Receive/AddressDetail.js]: image

File: src/components/Receive/AddressDetail.js [hunk 2]
```diff
@@ -14,7 +14,7 @@ type Props = {
 }
 
 const AddressDetail = ({address, translations}: Props) => (
-  <QRCode value={address} size={140} bgColor="#000" fgColor="#fff" />
+  <QRCode value={address} size={140} bgColor="white" fgColor="#fff" />
```
Comment (vantuz-subhuman) [inline src/components/Receive/AddressDetail.js]: should it be `while` here too, instead of `#fff`?
