### PR TITLE
fix wallet creation for small screens

### LINKED ISSUE #1155: Yoroi on Android 10 go
The 15 words appear on the first screen but only 14 on the 2nd , not really sure why? No scroll options

Took some photo evidence and the 2nd screen dropped to 13 xD 
IMG_20210117_030337
IMG_20210117_030214
IMG_20210117_030312
IMG_20210117_030235

New here so dno if I did images right...

### PR DESCRIPTION
**Pull request by wolverineks**
remove unnecessary `SafeAreaView`s
add `ScrollView` to accommodate smaller screens
remove fixed height for mnemonic words

tested on ipod Touch (simulator) and Galaxy Nexus (emulator), both with text and display at max and at default

closes #1155

### CODE REVIEW

File: src/components/WalletInit/CreateWallet/MnemonicCheckScreen.js [hunk 1]
```diff
@@ -143,75 +142,79 @@ const MnemonicCheckScreen = ({
   const last = _.last(partialPhrase)
 
   return (
-    <SafeAreaView style={styles.safeAreaView}>
```
Comment (v-almonacid) [inline src/components/WalletInit/CreateWallet/MnemonicCheckScreen.js:146]: What's the rationale for removing `SafeAreView`?

Comment (wolverineks) [reply src/components/WalletInit/CreateWallet/MnemonicCheckScreen.js:146]: my understanding is that `react-navigation` takes care of notches / status bars, etc...
so `<SafeAreaView>` would only be necessary in scenes that do not have a `react-navigation` header

Comment (wolverineks) [reply src/components/WalletInit/CreateWallet/MnemonicCheckScreen.js:146]: from the `react-navigation` docs
> React Navigation handles safe area in the default header. However, if you're using a custom header, it's important to ensure your UI is within the safe area.

Comment (v-almonacid) [reply src/components/WalletInit/CreateWallet/MnemonicCheckScreen.js:146]: Actually they only handle it for their components (eg. the navigation bar). Quoting from their docs:

> While React Navigation handles safe areas for the built-in UI elements by default, your own content also needs to handle it to ensure that content isn't hidden by these items.
> 
> (...)
> 
> While React Native exports a SafeAreaView component, it has some inherent issues, i.e. if a screen containing safe area is animating, it causes jumpy behavior. In addition, this component only supports iOS 10+ with no support for older iOS versions or Android. We recommend to use the react-native-safe-area-context library to handle safe areas in a more reliable way.
> 

I don't have many devices to check if this doesn't have unexpected effects, and probably for these screens there shouldn't be any issue, but as a general rule I'd prefer that we always wrap the content inside a `SafeAreaView` from `react-native-safe-area-content` in particular 🙏

Comment (wolverineks) [reply src/components/WalletInit/CreateWallet/MnemonicCheckScreen.js:146]: my understanding is that `<SafeAreaView>` adds the top/bottom padding regardless if the component would overlap the notches.
for instance, this is what im seeing on the ios simulator
ive added red borders around the `<SafeAreaView>` and `<WalletForm>`
Screen Shot 2021-04-26 at 13 14 30

Comment (wolverineks) [reply src/components/WalletInit/CreateWallet/MnemonicCheckScreen.js:146]: it doesnt do that on android
Screen Shot 2021-04-26 at 13 17 27

Comment (wolverineks) [reply src/components/WalletInit/CreateWallet/MnemonicCheckScreen.js:146]: might be related
https://github.com/th3rdwave/react-native-safe-area-context/issues/107

Comment (wolverineks) [reply src/components/WalletInit/CreateWallet/MnemonicCheckScreen.js:146]: oh i see what's happening.

i agree now, that each of the main scene components should be wrapped in a <SafeAreaView>`, but if the navigator uses a `react-navigation` header or footer, then the `<SafeAreaView>` also needs to specify the `edges` prop  to avoid double padding 
(but only in ios for some weird reason)

ill take a look at this again tomorrow

**Comment by wolverineks** [comment]
alright, `<SafeAreaView>` is back in, as well as removing the duplicated safe area padding at the top of the screens
`<ScrollView>` added to accommodate smaller screens
wrapped each section in a `<View>` for easier styling

**Comment by v-almonacid** [comment]
@wolverineks could you please increase the margin a little bit here 🙏 
image

The design specs show a 32px margin, but let me know if it looks like too much/too low/

Edit: wrong image

**Review by v-almonacid — APPROVED** [review]
I was able to reproduce and confirm the fix on a real device setting the text size to the maximum size.

Thank you @wolverineks !
